memgraph/docs

user_technical/quick-start.md

Introducing Memgraph's command-line tool `mg_client`.

Replace neo4j-client with mg_client in quick start

---

products/memgraph/v0.14.1/how_to_guides/import-data.md

The issues we received:
-  Headers without types sometimes break (our implementation has a default type which is not documented).
-  When trying to run the csv import tool with existing durability directory which has WAL files, the whole thing will crash
-  It's not clear how to import data stored in multiple files
-  It's not clear that csv import should be a one-time operation before running Memgraph. Therefore, users try to import data while they have a running Memgraph instance.

Improve mg_import_tool documentation

---

products/memgraph_cloud/how-to-connect.md

Link `https://memgraph.com/download/memgraph-lab` does not work.

Fix link to download Memgraph Lab

---

products/memgraph/upcoming/tutorials/analyzing-TED-talks.md
products/memgraph/upcoming/tutorials/backpacking-through-europe.md
products/memgraph/upcoming/tutorials/exploring-the-european-road-network.md
products/memgraph/upcoming/tutorials/football-transfers.md
products/memgraph/upcoming/tutorials/graphing-the-premier-league.md
products/memgraph/upcoming/tutorials/marvel-universe.md
products/memgraph/upcoming/tutorials/movie-recommendation.md

Having in each tutorial links to other tutorials makes it really hard to mantain.
Also, the list of tutorials isn't that short anymore.
This seems like a more managable solution while keeping the same functionality.

Replace links to each tutorial with link to tutorial overview

---

lab/getting-started.md

it seems the /overview suffix here is no longer valid

Correct URL to Cypher Manual from Getting Started

---

docs/database-functionalities/import-data.md
docs/tutorials/football-transfers.md
lab/installation/osx-installation.md
lab/style-script/reference-guide.md

Reading through the docs I found some spelling typos so I corrected them.
On a side note, there were 1054 lines with trailing spaces in the directory before this update. I just removed those within the files containing typos and checked changes don't affect the markdown render.
I can remove the trailing spaces on the remaining files in the project with a script but I'm worried some of the trailing spaces are [(mis)used](https://arcticicestudio.github.io/styleguide-markdown/rules/whitespace.html#trailing) intentionally to introduce a line break.

Fixing minor typos and trailing spaces

---

docs/database-functionalities/import-data.md
memgraph_versioned_docs/version-1.4.0/database-functionalities/import-data.md

@g-despot This is a wild swing PR. Please double-check if it makes sense.
I was playing around with Memgraph Lab and it seems that the FROM keyword is missing from the LOAD CSV examples.

Added missing FROM keyword to LOAD CSV instructions

---

cypher-manual/overview.md
docs/connect-to-memgraph/overview.md
docs/database-functionalities/overview.md
docs/database-functionalities/query-modules/overview.md
docs/import-data/overview.md
docs/installation/overview.md
docs/reference-guide/overview.md
docs/reference-guide/query-modules/overview.md
docs/reference-guide/streams/overview.md
docs/reference-guide/streams/transformation-modules/overview.md
docs/tutorials/overview.md
mage/overview.md
memgraph_versioned_docs/version-1.6.1/connect-to-memgraph/overview.md
memgraph_versioned_docs/version-1.6.1/database-functionalities/overview.md
memgraph_versioned_docs/version-1.6.1/database-functionalities/query-modules/overview.md
memgraph_versioned_docs/version-1.6.1/import-data/overview.md
memgraph_versioned_docs/version-1.6.1/installation/overview.md
memgraph_versioned_docs/version-1.6.1/reference-guide/overview.md
memgraph_versioned_docs/version-1.6.1/reference-guide/query-modules/overview.md
memgraph_versioned_docs/version-1.6.1/reference-guide/streams/overview.md
memgraph_versioned_docs/version-1.6.1/reference-guide/streams/transformation-modules/overview.md
memgraph_versioned_docs/version-1.6.1/tutorials/overview.md

Page names in the documentation hierarchy contain generic names like: "overview", "docker", and similar. This should be changed to "data import overview", "connect to Memgraph overview" and similar. The reason is the "step-by-step guide" we talked about. On the bottom of the page, the "next" article always shows the name of the next page. So for example, if you're positioned on the "connect to Memgraph" PHP page, the next page should be "import data overview", but it just says "overview".
I can make a pull request, but I'm unsure which files I need to change besides the actual file names of the pages.
Case in point: React Native documentation
The sub-menu is called "native modules", and the first page inside is called "native modules intro", not "intro".
Instead of modifying IDs and file …

Rename overview pages

---

cypher-manual/functions.md

Noticed that `any` is missing when answering [here](https://discourse.memgraph.com/t/returning-nodes-that-dont-have-a-certain-relationship) :smile:

Add any to cypher-manual

---

docs/installation/macos/docker-installation.md
docs/installation/windows/docker-installation.md
docs/installation/windows/windows-installation-troubleshooting.md
docs/installation/windows/wsl-installation.md
memgraph_versioned_docs/version-1.6.1/installation/macos/docker-installation.md
memgraph_versioned_docs/version-1.6.1/installation/windows/docker-installation.md
memgraph_versioned_docs/version-1.6.1/installation/windows/windows-installation-troubleshooting.md
memgraph_versioned_docs/version-1.6.1/installation/windows/wsl-installation.md

In windows, I had a few problems when installing Memgraph with docker.
1. WSL does need to be installed, even though we won't be using it directly, this is because docker is using it.
2. Experimental features need to be enabled in docker desktop
3. Docker volumes are completely unnecessary
4. It wasn't stated where to run commands (I added CMD and PowerShell options)

improve windows docker installation

---

docs/database-functionalities/streams/implement-transformation-module.md
docs/database-functionalities/streams/kafka-streams.md
docs/reference-guide/security.md
docs/reference-guide/streams/overview.md
docs/reference-guide/streams/transformation-modules/overview.md

The general idea of this PR is to reduce verbosity, and condense the documentation to a succinct form that is pleasant to read and navigate through.

update streaming docs

---

CONTRIBUTING.md
README.md
docusaurus.config.js
lab/style-script/quick-start.md
mage/overview.md
memgraph_versioned_sidebars/version-1.3.0-sidebars.json
memgraph_versioned_sidebars/version-1.4.0-sidebars.json
memgraph_versioned_sidebars/version-1.5.0-sidebars.json
memgraph_versioned_sidebars/version-1.6.0-sidebars.json
memgraph_versioned_sidebars/version-1.6.1-sidebars.json
package.json
sidebars/sidebarsMemgraph.js
static/CNAME

Relevant blog post explanation is in notion under engineering/general/website setup. *TODO* update this reference when the blog post gets published.
Tasks:

Transfer subdomain to subdirectory

---

docs/import-data/kafka/overview.md
memgraph_versioned_docs/version-1.6.1/import-data/kafka/overview.md

Some new `docs.memgraph.com` links emerged. We should be more careful about those when accepting pull requests.

fix wrong urls

---

docs/changelog.md
docs/reference-guide/streams/overview.md

Original PR is #240 was merged, but I used simple merge instead of squash merge. I force-pushed `release-2.1` to revert the merge.

[release-2.1 < T0762-MG] Add kafka set stream offset docs

---

docusaurus.config.js

We forgot to add these redirects before release 2.1

Add redirects for moving Kafka docs

---

docs/reference-guide/configuration.md

**Description**
Just changed the directory name in config settings for `--query-modules-directory` flag from `query-modules` to `query_modules`.
Closes https://github.com/memgraph/docs/issues/369

[master < T0658-DX] Change query modules directory name

---

docs/how-to-guides/overview.md
docs/how-to-guides/work-with-docker.md
docs/import-data/cypherl.md
docs/tutorials/first-steps-with-memgraph.md

I've updated the Docker how-to with a new slug and I've linked it from all of the existing docs.
We will need to update redirects once this PR is completed.

[master < T0714-DX] Link Docker how-to from existing docs

---

docs/changelog.md

Added information in the changelog with regards to the registration of replicas with identical end points (bug fix).

[release-2.4.0 < T0873] Forbid two replicas to point to the same ip port

---

docs/connect-to-memgraph/mgconsole.md
docs/how-to-guides/config-logs.md
docs/how-to-guides/encryption.md
docs/how-to-guides/streams/pulsar/implement-transformation-module.md
docs/how-to-guides/work-with-docker.md
docs/import-data/kafka/overview.md
docs/installation/linux/docker-db-installation.md
docs/installation/linux/docker-installation.md
docs/installation/macos/docker-db-installation.md
docs/installation/macos/docker-installation.md
docs/installation/windows/docker-db-installation.md
docs/installation/windows/docker-installation.md
docs/reference-guide/streams/transformation-modules/overview.md
docs/reference-guide/users.md
docs/templates/query-modules/_loading_query_modules.mdx
errors/memgraph/durability.md
errors/memgraph/ports.md
errors/memgraph/snapshots.md

Added another flag to clarify how multiple config flags should be passed in docker run command
Added info that mgconsole should be run manually when using memgraph and memgraph-mage images

[master<] Clarifying env var and mgconsole

---

docusaurus.config.js

Add a link for Memgraph Cloud to the footer of the documentation pages.

[master < T0831-DX] Memgraph Cloud to the footer of the documentation pages

---

docs/changelog.md
docs/how-to-guides/overview.md

I fixed one broken link in Memgraph Changelog and another in the how-to guides overview that had extra parenthesis.

[master < T0834-DX] Add two link fixes

---

docs/changelog.md

Fixed bug where certain aggregation functions gave non-openCypher  compliant results on `null` input. Updated Changelog accordingly.
Changelog.
Closes (https://github.com/memgraph/memgraph/pull/448)

Changelog update

---

docs/reference-guide/triggers.md

The link to the triggers how-to guide from the triggers reference was broken.

[master < T0865-DX] Fix triggers reference guide link

---

docs/reference-guide/streams/transformation-modules/overview.md

Fix path to internal_modules in transformation modules overview

[master<]Fix wrong path for internal_modules folder

---

docusaurus.config.js

Return support for remark and katex that has dropped out of the config file.

[master < update-docosaurus-config] Return support for remark and katex

---

docs/how-to-guides/streams/manage-streams.md
docs/import-data/data-streams/manage-streams.md
docs/reference-guide/streams/transformation-modules/api/c-api.md
docs/reference-guide/streams/transformation-modules/overview.md
memgraph_versioned_docs/version-2.3.1/how-to-guides/streams/manage-streams.md
memgraph_versioned_docs/version-2.3.1/import-data/data-streams/manage-streams.md
memgraph_versioned_docs/version-2.3.1/reference-guide/streams/transformation-modules/api/c-api.md
memgraph_versioned_docs/version-2.3.1/reference-guide/streams/transformation-modules/overview.md

Change the path to internal modules to /var/lib/memgraph/internal_modules

[master<]Fix the path to internal modules folder

---

cypher-manual/clauses/merge.md

Fixed links on the MERGE clause page of cypher manual
https://github.com/memgraph/docs/issues/521

[master<] Fixing links on the MERGE clause page in Cypher manual

---

docs/how-to-guides/encryption.md
docs/reference-guide/encryption.md
memgraph_versioned_docs/version-2.3.1/how-to-guides/encryption.md
memgraph_versioned_docs/version-2.3.1/reference-guide/encryption.md

Fixed broken links in the encryption how-to and ref guide
Closes [(link to issue)](https://github.com/memgraph/docs/issues/540)

[master<] Fix broken links in encryption docs

---

src/theme/sections/home-playground-embed/home-playground-embed.js

I updated the Playground embed on the home page of the docs. It didn't render well before.
Closes https://github.com/memgraph/docs/issues/571

[master < T0974-DX] Update Playground embed

---

docs/changelog.md
docs/getting-started.md
docs/reference-guide/query-modules/implement-custom-query-modules/overview.md
docs/reference-guide/replication.md
mage/how-to-guides/run-a-query-module.md
mage/installation/docker-build.md
memgraph_versioned_docs/version-2.1.1/getting-started.md
memgraph_versioned_docs/version-2.2.0/getting-started.md
memgraph_versioned_docs/version-2.2.1/getting-started.md
memgraph_versioned_docs/version-2.3.0/getting-started.md
memgraph_versioned_docs/version-2.3.1/getting-started.md
memgraph_versioned_docs/version-2.4.0/changelog.md
memgraph_versioned_docs/version-2.4.0/getting-started.md
memgraph_versioned_docs/version-2.4.0/reference-guide/replication.md
memgraph_versioned_docs/version-2.4.1/changelog.md
memgraph_versioned_docs/version-2.4.1/getting-started.md
memgraph_versioned_docs/version-2.4.1/reference-guide/replication.md
memgraph_versioned_docs/version-2.4.2/changelog.md
memgraph_versioned_docs/version-2.4.2/getting-started.md
memgraph_versioned_docs/version-2.4.2/reference-guide/query-modules/implement-custom-query-modules/overview.md
memgraph_versioned_docs/version-2.4.2/reference-guide/replication.md

Listed issues +  "under tabs Docker hub and Docker build , the dev version of the image needs to be prefixed with a version https://memgraph.com/docs/mage/how-to-guides/run-a-query-module"
Closes https://github.com/memgraph/docs/issues/596
Closes https://github.com/memgraph/docs/issues/574
Closes https://github.com/memgraph/docs/issues/567

[master<] Fixing several small issues 

---

cloud/cloud-connect.md
docs/connect-to-memgraph/drivers/c-sharp.md
memgraph_versioned_docs/version-2.3.0/connect-to-memgraph/drivers/c-sharp.md
memgraph_versioned_docs/version-2.3.1/connect-to-memgraph/drivers/c-sharp.md
memgraph_versioned_docs/version-2.4.0/connect-to-memgraph/drivers/c-sharp.md
memgraph_versioned_docs/version-2.4.1/connect-to-memgraph/drivers/c-sharp.md
memgraph_versioned_docs/version-2.4.2/connect-to-memgraph/drivers/c-sharp.md

I updated C# quick start guide in the next and current versions. I deleted Cloud docs for the C# driver because it's still not possible to connect to a Cloud instance with the C# driver (`--bolt-server-name-for-init` needs to be reconfigured).

Update C# quick start

---

docs/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md

Fix the type hint bug and added authorization type error missing from previous additons to mgp.py
This relates to an issue repoted here: https://github.com/memgraph/memgraph/issues/692

[MASTER < DX1012] Update python API  and fix type hint  bug. 

---

docs/how-to-guides/create-backup.md
docs/reference-guide/backup.md

* Mention recovery in [How to create a backup](https://memgraph.com/docs/memgraph/how-to-guides/create-backup)
* extend [Data durability](https://memgraph.com/docs/memgraph/reference-guide/backup) with disaster recovery, `DUMP DATABASE` and configuration

[master < T553-FL] Extend backup & restore docs to address user questions 

---

docs/how-to-guides/replication.md
docs/reference-guide/replication.md
docs/under-the-hood/replication.md
memgraph_versioned_docs/version-2.5.0/how-to-guides/replication.md
memgraph_versioned_docs/version-2.5.0/reference-guide/replication.md
memgraph_versioned_docs/version-2.5.1/how-to-guides/replication.md
memgraph_versioned_docs/version-2.5.1/reference-guide/replication.md
memgraph_versioned_docs/version-2.5.2/how-to-guides/replication.md
memgraph_versioned_docs/version-2.5.2/reference-guide/replication.md

Added a link to finding instance IP address in Docker
Removed that the MAIN will receive an error if a SYNC instance is unavaliable
Closes https://github.com/memgraph/docs/issues/708

[master<231402] Replication docs fix

---

cypher-manual/clauses/where.md
cypher-manual/differences-in-cypher-implementations.md
cypher-manual/functions.md

Where exists is the first feature with pattern expressions in filters. Users don't need to do optional match but directly use WHERE exists after match clauses

Add docs for where exists

---

docs/reference-guide/query-modules/implement-custom-query-modules/api/mock-python-api.md
docs/reference-guide/query-modules/implement-custom-query-modules/overview.md
docs/reference-guide/query-modules/overview.md
mage/how-to-guides/create-a-new-module-python.md
mage/usage/loading-modules.md
sidebars/sidebarsMemgraph.js

Documentation for [PR#757](https://github.com/memgraph/memgraph/pull/757).
Changelog message (in Major features and improvements):
>  With the new Python mock query module API, you can now develop and test Python query modules for Memgraph without having to run a Memgraph instance. The mock API is compatible with the Python API and thus developed modules can be added to Memgraph as-is.
PR this doc page is related to: [PR#757](https://github.com/memgraph/memgraph/pull/757)

Python mock API documentation

---

docs/reference-guide/graph-algorithms.md

Fixes a cypher example for `*ALLSHORTEST` algorithm here: https://memgraph.com/docs/memgraph/reference-guide/built-in-graph-algorithms#getting-various-results-3 . The example is for `*WSHORTEST`.
None
(Not sure that these apply in such a small patch):

fix total weight example in ASP doc

---

docs/changelog.md
docs/reference-guide/configuration.md

Update reference guide with the newly added flag that enables/disables using multiple threads of execution for creating indicies.
https://github.com/memgraph/memgraph/pull/882

[release-v2.8.0] < [MG-parallelize-index-creation]

---

docs/changelog.md
docs/reference-guide/configuration.md
docs/reference-guide/enterprise-features.md
docs/reference-guide/exposing-system-metrics.md
docs/reference-guide/optimizing-queries/inspecting-queries.md
memgraph_versioned_docs/version-2.8.0/changelog.md
memgraph_versioned_docs/version-2.8.0/reference-guide/configuration.md
memgraph_versioned_docs/version-2.8.0/reference-guide/enterprise-features.md
memgraph_versioned_docs/version-2.8.0/reference-guide/exposing-system-metrics.md
memgraph_versioned_docs/version-2.8.0/reference-guide/optimizing-queries/inspecting-queries.md
memgraph_versioned_sidebars/version-2.8.0-sidebars.json
sidebars/sidebarsMemgraph.js

Docs explain the new feature in Memgraph v2.8 - exposing system metrics via an HTTP endpoint. With this feature, users are able to get metrics about various information in the system (info about transactions, streams, query latencies, indexes, etc.) so they can react properly and be aware to changes in the system

Add exposing metrics via HTTP endpoint

---

docs/connect-to-memgraph/mgconsole.md
memgraph_versioned_docs/version-2.7.0/connect-to-memgraph/mgconsole.md
memgraph_versioned_docs/version-2.8.0/connect-to-memgraph/mgconsole.md

Fixed typo in mgconsole flag documentation.

[master < fiy-typo-20230524] Fix typo in mgconsole flag documentation

---

docs/reference-guide/backup.md

Inserting a snapshot file before Memgraph is started, in purly created container.  The issue is with file ownershiop, you are not able to give a proper file ownership outside of conatiner, this is solution for that type of scenario. 
Closes https://github.com/memgraph/memgraph/issues/926

Add option to insert the snapshot file during creation of container

---

docs/reference-guide/users.md
memgraph_versioned_docs/version-2.5.0/reference-guide/users.md
memgraph_versioned_docs/version-2.5.1/reference-guide/users.md
memgraph_versioned_docs/version-2.5.2/reference-guide/users.md
memgraph_versioned_docs/version-2.6.0/reference-guide/users.md
memgraph_versioned_docs/version-2.7.0/reference-guide/users.md
memgraph_versioned_docs/version-2.8.0/reference-guide/users.md

Update docs related to user creation with or without a password.
Closes (link to issue): https://github.com/memgraph/docs/issues/929

[master < 929-change-create-user-query] Update docs related to user accounts

---

docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md

MGP Any type enables users to pass any type as argument in the C++ query module without specifying it prior to running Memgraph.

Add any type to documentation

---

docs/reference-guide/transactions.md

We added support for user-defined transaction metadata. The user can pass additional information via a dictionary. 
This was implemented because users complained that distinguishing between multiple similar transactions was difficult.
Now they can add a uuid to each transaction, call show transaction and filter out the exact transaction they are interested in.
https://github.com/memgraph/memgraph/pull/945

[master < ] Transaction metadata

---

cypher-manual/clauses/load-csv.md
docs/import-data/files/load-csv-clause.md

Entering MATCH or MERGE before LOAD CSV can now be done if it results in yielding only one row. Yielding multiple rows before calling LOAD CSV will result in an error.

[master < T922] Add documentation for MATCH + LOAD CSV

---

mage/query-modules/cpp/create.md

Added documentation for my part of create procedures.
PR this doc page is related to: https://github.com/memgraph/mage/pull/318

[E-create < E-idora-create] Add docs for create module

---

mage/query-modules/cpp/create.md

[E-create < E-ivan] Add create docs
