user_technical/open-cypher.md
Remove symbolic names from the list of unsupported features
=> Remove symbolic names from the list of unsupported features

user_technical/README.md, user_technical/tutorials/analyzing-TED-talks.md, user_technical/tutorials/exploring-the-european-road-network.md, user_technical/tutorials/graphing-the-premier-league.md, user_technical/tutorials/movie-recommendation.md, user_technical/tutorials/tutorials-overview.md
The tutorial shows how to implement a simple recommendation system.
=> Movie tutorial added

products/memgraph/v0.12.0/faq.md, products/memgraph/v0.13.0/concepts/graph-algorithms.md, products/memgraph/v0.13.0/faq.md, products/memgraph/v0.13.0/reference_guide/indexing.md, products/memgraph/v0.14.0/concepts/graph-algorithms.md, products/memgraph/v0.14.0/faq.md, products/memgraph/v0.14.0/reference_guide/indexing.md, products/memgraph/v0.15.0/concepts/graph-algorithms.md, products/memgraph/v0.15.0/faq.md, products/memgraph/v0.15.0/reference_guide/indexing.md
The fixes were applied to all of the available versions. I can undo them for the older versions if there's a policy regarding that.
=> Minor grammar fixes

products/memgraph/v0.15.0/README.md, products/memgraph/v0.15.0/how_to_guides/explain-profile.md, products/memgraph/v0.15.0/how_to_guides/how-to-guides-overview.md, products/memgraph/v0.15.0/reference_guide/other-features.md
I'm not completely sure how detailed we want to be about the internals such as the plan and the logical operators. Also, perhaps some of these examples could be moved into a separate how-to section.
Here's a first shot at it. Feel free to suggest improvements.
=> Explain `EXPLAIN` and `PROFILE`

products/memgraph/v0.15.0/README.md, products/memgraph/v0.15.0/tutorials/analyzing-TED-talks.md, products/memgraph/v0.15.0/tutorials/backpacking-through-europe.md, products/memgraph/v0.15.0/tutorials/exploring-the-european-road-network.md, products/memgraph/v0.15.0/tutorials/graphing-the-premier-league.md, products/memgraph/v0.15.0/tutorials/movie-recommendation.md, products/memgraph/v0.15.0/tutorials/tutorials-overview.md
Add the 'Backpacking through Europe' tutorial and link it to other tutorials.
=> Add new backpacking tutorial

products/.gitbook_readme
Change Introduction to Overview and add versions for each product
=> Polish gitbook pages

products/memgraph/upcoming/how_to_guides/import-data.md, products/memgraph/upcoming/quick-start.md
* Update mg_client with explicit --use-ssl=False usage because the default has
changed on the server-side
=> Put deprecation note about mg_client

products/memgraph/upcoming/tutorials/replication.md, products/memgraph/upcoming/tutorials/tutorials.md
* initial version - setting up the cluster using Docker
* ToDo:  add a more complex example
=> Replication tutorial

products/memgraph/upcoming/concepts/concepts-overview.md, products/memgraph/upcoming/concepts/replication.md, products/memgraph/upcoming/reference_guide/replication.md
* added replication sections to `Concepts` and `Reference guide`
=> Add replication concepts and reference guide

docs/tutorials/understanding-music-with-modules.md, memgraph_versioned_docs/version-1.4.0/tutorials/understanding-music-with-modules.md
=> Understanding music with modules Cypher fix

docs/tutorials/social-network-analysis.md, memgraph_versioned_docs/version-1.4.0/tutorials/social-network-analysis.md
=> Social network analysis Cypher fix

docs/tutorials/movie-recommendation.md, memgraph_versioned_docs/version-1.4.0/tutorials/movie-recommendation.md
A big one, but should be easy to review...
=> Movie recommendation Cypher fix

docs/tutorials/marvel-universe.md, memgraph_versioned_docs/version-1.4.0/tutorials/marvel-universe.md
Fixing cypher styling and 2 new query alternatives added.
=> Marvel Universe Cypher fix

docs/tutorials/graphing-the-premier-league.md, memgraph_versioned_docs/version-1.4.0/tutorials/graphing-the-premier-league.md
Should be fast and easy to review.
=> Graphing the Premier League Cypher fix

docs/tutorials/got-deaths.md, memgraph_versioned_docs/version-1.4.0/tutorials/got-deaths.md
This one should be fast and straight forward to review :)
=> GoT Deaths Cypher styling fix

docs/tutorials/football-transfers.md, memgraph_versioned_docs/version-1.4.0/tutorials/football-transfers.md
This one is going to be painful to review.
Many, many changes...
=> Football transfers cypher fix

docs/database-functionalities/triggers.md, sidebarsMemgraph.js
* fixed tables
* fixed no-bullets list
=> Fix triggers.md

src/components/callout-box/callout-box.js, src/components/callout-box/callout-box.module.css, src/components/link-right-arrow/link-right-arrow.js, src/components/link-right-arrow/link-right-arrow.module.css, src/css/custom.css, src/theme/sections/home-get-involved/home-get-involved.js, src/theme/sections/home-get-involved/home-get-involved.module.css
This PR improves on several issues caused when the user sets the minimal font in his browser to higher than 16px.
📓 Changes:
1. Links with arrows should work in a way that they are always aligned in one row (the arrow doesn't fold in another row anymore).
2. Get Involved section responsiveness improved. On smaller screens, it folds the two columns into rows.
=> Accessibility fixes

docs/reference-guide/query-modules/api/c-api.md
Don't forget that you can ignore whitespace changes while looking at the diff. :smile:
=> Document global allocation functions

docs/getting-started.md, memgraph_versioned_docs/version-1.6.1/getting-started.md
=> update getting started page

docs/reference-guide/streams/transformation-modules/api/python-api.md, memgraph_versioned_docs/version-1.6.1/reference-guide/streams/transformation-modules/api/python-api.md
=> refactor base instructions for creating a transformation module.

docs/changelog.md, memgraph_versioned_docs/version-2.1.0/changelog.md
I forgot about deciding not to fix compatibility breaking.
=> Remove the promise of fixing

docs/concepts/concepts.md, docs/getting-started.md, docusaurus.config.js, src/theme/sections/home-callouts/home-callouts.js
=> Implement minor menu and documentation changes

docs/import-data/csv-import-tool.md
=> [master < T0324-DX]Implement minor menu and documentation changes

docs/import-data/load-csv-clause.md, memgraph_versioned_docs/version-2.1.1/import-data/load-csv-clause.md
=> Transferring CSV files to Docker container for LOAD CSV clause

mage/how-to-guides/create-a-new-module-cpp.md, mage/how-to-guides/create-a-new-module-python.md
Fixes and improvements to #239.
=> Improve C++ dev guide documentation

docs/installation/linux/debian-installation.md, docs/installation/linux/docker-db-installation.md, docs/installation/linux/docker-installation.md, docs/installation/linux/linux-installation-troubleshooting.md, docs/installation/linux/rpm-installation.md, docs/installation/linux/ubuntu-installation.md, docs/installation/macos/docker-db-installation.md, docs/installation/macos/docker-installation.md, docs/installation/macos/macos-installation-troubleshooting.md, docs/installation/overview.md, docs/installation/windows/docker-db-installation.md, docs/installation/windows/docker-installation.md, docs/installation/windows/windows-installation-troubleshooting.md, docs/installation/windows/wsl-installation.md, docusaurus.config.js, memgraph_versioned_docs/version-2.1.1/getting-started.md, sidebars/sidebarsMemgraph.js
Change in the Install Memgraph structure
Links need to be checked and changed (especially on the overview page)
=> [T0406 < T0421] Update Install Memgraph pages

docs/connect-to-memgraph/drivers/c-sharp.md, docs/connect-to-memgraph/drivers/javascript.md, docs/connect-to-memgraph/drivers/nodejs.md, docs/connect-to-memgraph/drivers/overview.md, docs/connect-to-memgraph/drivers/rust.md, docs/connect-to-memgraph/mgconsole.md, docs/connect-to-memgraph/overview.mdx, memgraph_versioned_docs/version-2.1.1/connect-to-memgraph/drivers/c-sharp.md, memgraph_versioned_docs/version-2.1.1/connect-to-memgraph/drivers/javascript.md, memgraph_versioned_docs/version-2.1.1/connect-to-memgraph/drivers/nodejs.md, memgraph_versioned_docs/version-2.1.1/connect-to-memgraph/drivers/overview.md, memgraph_versioned_docs/version-2.1.1/connect-to-memgraph/drivers/rust.md, memgraph_versioned_docs/version-2.1.1/connect-to-memgraph/mgconsole.md, memgraph_versioned_docs/version-2.1.1/connect-to-memgraph/overview.mdx, memgraph_versioned_sidebars/version-2.1.1-sidebars.json, sidebars/sidebarsMemgraph.js
[x] Rearranged items in the side menu and overview page
[x] Few extra sentences in the mgconsole page
[x] Minor language changes
=> (master < T0421-DX) Update Connect2Memgraph

docs/import-data/csv-import-tool.md, docs/import-data/cypherl.md, docs/import-data/kafka/avro.md, docs/import-data/kafka/json.md, docs/import-data/kafka/overview.md, docs/import-data/kafka/protobuf.md, docs/import-data/load-csv-clause.md, docs/import-data/migrate/mysql.md, docs/import-data/migrate/postgresql.md, docs/import-data/overview.mdx
The links on the cypherl page in the html code need to be adjusted
=> [T0410-DX HotJar fixes < T0421-DX] Update import data

docs/import-data/csv-import-tool.md, memgraph_versioned_docs/version-2.1.1/import-data/csv-import-tool.md
I 've added `-it` and exposed `-p 3000:3000` in the docker run command
=> [master<bugFix] Import Tool Docker Run Command Fix

docusaurus.config.js
This is a PR just for docs banner because I have to wait for the design requirements to create new components.
=> [master <  T0538-DX] Add Cypher Email Course banner

docs/import-data/kafka/overview.md, docs/tutorials/graph-stream-processing-with-kafka.md, docs/tutorials/migrate-relational-database.md, docs/tutorials/style-your-graphs-in-memgraph-lab.md, help-center/faq/memgraph-lab-faq.md, lab/getting-started.md, lab/style-script/reference-guide.md
=> [master < T0619-DX] Replace Style script with Graph Style Script

gqlalchemy/how-to-guides/ogm/index-labels-and-properties.md, gqlalchemy/how-to-guides/ogm/load-nodes-and-relationships.md, gqlalchemy/how-to-guides/ogm/map-nodes-and-relationships.md, gqlalchemy/how-to-guides/ogm/save-nodes-and-relationships.md, sidebars/sidebarsGQLAlchemy.js
=> [T0037-GA < T0042-GA] Create how-to guide for indexing

gqlalchemy/how-to-guides/instance-runner/memgraph-binary-instance.md, gqlalchemy/how-to-guides/instance-runner/memgraph-docker-instance.md, gqlalchemy/how-to-guides/overview.md, sidebars/sidebarsGQLAlchemy.js
=> [T0037-GA < T0047-GA] Add instance runner how-to guides

gqlalchemy/how-to-guides/loaders/import-table-data-to-graph-database.md, gqlalchemy/how-to-guides/loaders/make-a-custom-file-system-importer.md, gqlalchemy/how-to-guides/overview.md
Updated the how-to guides overview with missing links to all guides.
=> [master <  T0069-GA] Update GQLAlchemy how-to guides overview

docs/connect-to-memgraph/drivers/overview.md, docs/how-to-guides/config-logs.md, docs/how-to-guides/replication.md, docs/installation/linux/docker-installation.md, docs/installation/macos/docker-installation.md, docs/installation/windows/docker-installation.md, docs/tutorials/implement-custom-query-module-in-python.md, docs/tutorials/migrate-relational-database.md, docs/tutorials/social-network-analysis.md, errors/memgraph/ssl.md
1. Changed some basic info about SSL
2. Added a missing step in changing the config file when running Memgraph with Docker / added another option how to change the file
3. Created links out of all `localhost:3000` 
4. Fixed some small language issues with the QM tutorial
=> Missing-information

cypher-manual/clauses/merge.md
=> [master<T0651] MERGE clause expanding

docs/tutorials/first-steps-with-memgraph.md
=> [master < T0706-DX] Fix color value in GSS code

src/pages/index.js, src/theme/sections/home-playground-embed/home-playground-embed.js, src/theme/sections/home-playground-embed/home-playground-embed.module.css
I added a Playground embed to Docs homepage.
=> [master < T0609-DX] Add Playground embed

docs/installation/direct-download-links.md
=> [master < T407-DX] Create new page with direct download links

docs/how-to-guides/work-with-docker.md, docs/reference-guide/deployment/docker.md, sidebars/sidebarsMemgraph.js
I have created the **Docker** section under the **Deployment** section in the **Reference guide**. The plan is to have the **Kubernetes** section under Deployment too.
=> [master <  T0541-DX] Add docker-compose files to docs

docs/installation/linux/debian-installation.md, docs/installation/linux/rpm-installation.md, docs/installation/linux/ubuntu-installation.md
I've replaced existing direct download links with a link that goes to a page that has all of the links listed on them.
=> [master < T0713-DX] Add links to direct download page

gqlalchemy/how-to-guides/query-builder/create-nodes-relationships.md, gqlalchemy/how-to-guides/query-builder/filter-data.md, gqlalchemy/reference/query_builder.md
In this PR I will be fixing GQLAlchemy docs regarding the renaming of **edge** to the **relationship**.
=> [T0084-GA < T0082-GA] Fix edge in query builder

cypher-manual/graph-algorithms.md, docusaurus.config.js, sidebars/sidebarsCypherManual.js
Add new algorithms page to cypher manual
=> [master < T0716-DX] Add algorithms to cypher manual

docs/reference-guide/deployment/kubernetes.md, docs/reference-guide/overview.md, sidebars/sidebarsMemgraph.js
I added a simple Memgraph Helm Chart as a part of the Kubernetes Deployment in the Reference guide. I also added Deployment to the Reference guide overview page.
=> [master < T0704-DX] Add Memgraph Helm Chart

docs/tutorials/implement-custom-query-module-in-python.md
Changed variable type + removed superfluous commas
=> [master<] Code fix in query module tutorial

gqlalchemy/how-to-guides/loaders/import-table-data-to-graph-database.md, gqlalchemy/how-to-guides/loaders/make-a-custom-file-system-importer.md
Azure Blob needs to be used with these changed kwargs.
=> renamed Azure Blob kwargs to adlfs specified ones

docs/tutorials/first-steps-with-memgraph.md, docs/tutorials/style-your-graphs-in-memgraph-lab.md
=> Update GSS code

docs/connect-to-memgraph/drivers/c-sharp.md, docs/connect-to-memgraph/drivers/go.md, docs/connect-to-memgraph/drivers/java.md, docs/connect-to-memgraph/drivers/nodejs.md, docs/connect-to-memgraph/drivers/php.md, docs/connect-to-memgraph/drivers/python.md, docs/connect-to-memgraph/drivers/rust.md
Updated the driver quick start guides. They have been tested with Memgraph 2.3.0.
=> [master < T0194-DX-update-drivers] Update quick start guides for drivers

docs/changelog.md
Added information in changelog with regards to the Memory Allocator's memory usage count.
=> [release-2.4.0 < T0807] Adding changelog for Memory allocator issue.

gqlalchemy/changelog.md
In this PR all changes will be updated in the changelog.
=> [T0084-GA < T0085-GA] Create changelog

gqlalchemy/getting-started.md, gqlalchemy/how-to-guides/instance-runner/memgraph-binary-instance.md, gqlalchemy/how-to-guides/instance-runner/memgraph-docker-instance.md, gqlalchemy/how-to-guides/loaders/import-table-data-to-graph-database.md, gqlalchemy/how-to-guides/loaders/make-a-custom-file-system-importer.md, gqlalchemy/how-to-guides/ogm/index-labels-and-properties.md, gqlalchemy/how-to-guides/ogm/load-nodes-and-relationships.md, gqlalchemy/how-to-guides/ogm/map-nodes-and-relationships.md, gqlalchemy/how-to-guides/ogm/save-nodes-and-relationships.md, gqlalchemy/how-to-guides/on-disk-storage/on-disk-storage.md, gqlalchemy/how-to-guides/query-builder/call-procedures.md, gqlalchemy/how-to-guides/query-builder/create-nodes-relationships.md, gqlalchemy/how-to-guides/query-builder/delete-remove-objects.md, gqlalchemy/how-to-guides/query-builder/filter-data.md, gqlalchemy/how-to-guides/query-builder/return-results.md, gqlalchemy/how-to-guides/query-builder/set-or-update-objects.md, gqlalchemy/how-to-guides/streams/kafka-streams.md, gqlalchemy/how-to-guides/streams/pulsar-streams.md, gqlalchemy/how-to-guides/triggers/triggers.md, gqlalchemy/templates/_neo4j_option.mdx, gqlalchemy/templates/_neo4j_warning.mdx
=> [master < T0105-GA] Add notes about Neo4j support

docs/import-data/csv/overview.md, docs/import-data/overview.mdx, docs/reference-guide/import-data/overview.md, sidebars/sidebarsMemgraph.js
=> [master < T0748-DX] Update CSV import documentation

docs/changelog.md, docs/how-to-guides/streams/kafka/kafka-streams.md, docs/how-to-guides/streams/pulsar/pulsar-streams.md, docs/import-data/kafka/overview.md, docs/reference-guide/streams/overview.md
**[memgraph PR](https://github.com/memgraph/memgraph/pull/392)**
=> [release-2.4.0 < T0642] Add limit batches option to start stream query

docs/how-to-guides/config-logs.md, docs/how-to-guides/streams/kafka/connect-to-stream-from-lab.md
* added a port 7444 missing on config-logs how-to
* preposition mission on the how to connect to a stream in lab
=> [master<T0781] Fixes to the docs pending the release

cloud/cloud-account.md, cloud/cloud-projects.md, cloud/payment.md
=> [master < cloud-docs-formatting] Update documentation formatting

docs/changelog.md
Updated Changelog. 
Code [PR](https://github.com/memgraph/memgraph/pull/412)
=> [release-2.4.0 < T0880-MG]  Add information on show replicas to express how uptodate is replica

gqlalchemy/how-to-guides/overview.md, gqlalchemy/how-to-guides/query-builder/filter-data.md, gqlalchemy/how-to-guides/query-builder/return-results.md, gqlalchemy/how-to-guides/query-builder/set-or-update-objects.md
I updated the imports in the GQLAlchemy query builder how-to guides. I also updated the overview for the query builder how-to guides.
=> [master <  T0110-GA] Update GQLAlchemy how-to guides

docusaurus.config.js, help-center/faq/cloud-faq.md, help-center/faq/memgraph-faq.md, sidebars/sidebarsHelpCenter.js
Created Memgraph Cloud FAQ document
=> [master < T0799-dx] Create Memgraph Cloud FAQ document

docs/changelog.md
Updated changelog for 2.3.1 release
=> [master < release-2.3.1] Add v2.3.1 updates

docs/import-data/kafka/overview.md
=> [master < T0805-DX] Update links

docs/changelog.md, docs/how-to-guides/replication.md, docs/reference-guide/replication.md, docs/under-the-hood/replication.md
Updated Changelog.
Adapted documentation of REGISTER REPLICA whenever TIMEOUT was mentioned.
Code [PR](https://github.com/memgraph/memgraph/pull/423)
=> [release-2.4.0 < T0890-MG] Updating changelog w.r.t TIMEOUT parameter of REGISTER REPLICA.

docs/how-to-guides/indexes.md, docs/reference-guide/indexing.md
Added a tip to create an index on unique integers.
=> indexing-tip

docusaurus.config.js
Update banner on docs to link to graph modeling course.
=> [master < change-banner-to-email-course] Update banner

cypher-manual/other-features.md, docs/changelog.md
Continuation PR for https://github.com/memgraph/docs/pull/458
Closes (https://github.com/memgraph/memgraph/pull/432)
=> [release-2.4.0 < T0899-MG] Modify changelog to describe bugfixes

src/theme/sections/home-callouts/home-callouts.js, src/theme/sections/home-get-involved/home-get-involved.js, src/theme/sections/home-get-involved/home-get-involved.module.css, src/theme/sections/home-playground-embed/home-playground-embed.module.css, static/img/cypher-email-course.svg
- Added link to Getting started with Cloud on the homepage
- Fixed Cypher Email Course icon resizing and bumped 'Master graph algorithms in minutes' to the left side - we could maybe update this to Graph Modelling Course? @kgolubic 
- Added right arrows to the links below social icons
=> [master < T0776-DX] Add Cloud on homepage

src/theme/sections/home-playground-embed/home-playground-embed.js
=> [master < T0835-DX] Add link to Playground

lab/style-script/gss-functions.md
Three new GSS functions will be in the upcoming Lab release: `Floor`, `Round`, and `Ceil`.
=> [master < T2358-CL] Add docs for new GSS functions: Round, Floor, and Ceil

gqlalchemy/getting-started.md
I added one sentence in Getting started with GQLAlchemy about Conda installation.
=> [master < T0819-DX] Add info about Conda installation of GQLAlchemy

docs/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md
=> [master < T0762] Rewrite Python API comments and snippets

WRITING_STYLE.md, docs/reference-guide/graph-algorithms.md, docusaurus.config.js, sidebars/sidebarsMemgraph.js
- Add redirects for missing URLs. 
- Update Graph algorithm page ID
=> [master < T0830-DX] Update redirects

docs/tutorials/implement-custom-query-module-in-python.md
=> [T0842-DX] Fix query module tutorial.

docusaurus.config.js
Update file with redirects.
Closes [issue 483](https://github.com/memgraph/docs/issues/483)
=> [master < T0830-v3] Update broken link

docs/getting-started.md
Added links to our email courses.
=> [master < T0836-DX} Add links to email courses

docs/how-to-guides/config-logs.md, docs/how-to-guides/work-with-docker.md, docs/import-data/kafka/overview.md, docs/installation/linux/docker-installation.md, docs/installation/macos/docker-installation.md, docs/installation/windows/docker-installation.md, docs/reference-guide/encryption.md, docs/reference-guide/streams/transformation-modules/overview.md, docs/reference-guide/users.md, docs/templates/query-modules/_loading_query_modules.mdx
Changed the term "environmental variables" to "environment variables"
=> [master<] Environment variables

cloud/getting-started.md
Fixed extra character in Getting started with Cloud docs page.
=> [master < T0866-DX] Fix typo

docs/connect-to-memgraph/drivers/php.md, memgraph_versioned_docs/version-2.3.1/connect-to-memgraph/drivers/php.md
Updated to latest version of PHP Bolt library.
Outdated documentation.
=> Updated docs for connecting PHP to memgraph

docs/reference-guide/transaction-handling.md
New page for transaction handling
=> [master<T0731] Transaction handling

docs/import-data/data-streams/manage-streams.md, docs/import-data/data-streams/overview.md, docs/reference-guide/streams/overview.md, docs/tutorials/graph-stream-processing-with-kafka.md, docs/under-the-hood/overview.md, memgraph_versioned_docs/version-2.3.1/import-data/data-streams/manage-streams.md, memgraph_versioned_docs/version-2.3.1/import-data/data-streams/overview.md, memgraph_versioned_docs/version-2.3.1/reference-guide/streams/overview.md, memgraph_versioned_docs/version-2.3.1/tutorials/graph-stream-processing-with-kafka.md, memgraph_versioned_docs/version-2.3.1/under-the-hood/overview.md
On documentation about streams, I've removed Tutorial label (BCS I didn't find it appropriate) and added How to label 
In the tutorial about connecting to streams intro, I made clear that we are working with Memgraph Lab
I've corrected the overview page of Under the hood
=> [master<] Fix pages after docs update

docs/changelog.md, docs/how-to-guides/config-logs.md, docs/how-to-guides/manage-user-privileges.md, docs/reference-guide/auth-module.md, docs/reference-guide/configuration.md
Modify Changelog by adding the new SHOW CONFIG command and updating the Configuration Settings page with the command.
Closes (https://github.com/memgraph/memgraph/issues/397)
[Memgraph PR](https://github.com/memgraph/memgraph/pull/459)
=> [release-2.4.0 < T0976-MG] Add command to return startup config

docusaurus.config.js
Add new redirects for documentation that was moved.
Closes ([514](https://github.com/memgraph/docs/issues/514))
=> [master < T0910-DX] Add new redirects

docs/how-to-guides/manage-user-privileges.md, docs/reference-guide/security.md
Some privileges were missing in the docs.
=> [master<] Add missing privileges

docs/installation/overview.mdx, docs/tutorials/first-steps-with-memgraph.md
I've added available Docker images at the end of the installation overview page. 
I've added drive to cloud sentence at the end of the First steps with Memgraph page (too small task for separate PR)
Closes https://github.com/memgraph/docs/issues/525
=> [master<T0929-DX] Mentioning Docker images

mage/overview.md
I've added a link to the MAGE GitHub repo.
Closes (#531 )
=> [master < 531-add-link-to-mage-repo] Add link to MAGE GitHub repo

docs/how-to-guides/config-logs.md, docs/reference-guide/configuration.md
Added SHOW CONFIG to config-log how to
Removed extra = in Kafka boostrap config flag
=> [release-2.4.0<] Small doc fixes

docs/reference-guide/graph-algorithms.md, memgraph_versioned_docs/version-2.3.1/reference-guide/graph-algorithms.md
In the reference guide page about built-in algorithms, I've highlighted the info where to find more algorithms and added a link to the algorithm list.
=> [master< ] Highlight algorithms

README.md, package.json
Add minimal node version to README.md and package.json.
Closes (#537)
=>  [master < 537-update-minimal-nodejs-version] Add minimal node version

cypher-manual/functions.md, docs/reference-guide/query-modules/implement-custom-query-modules/api/c-api.md, docs/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md, docs/templates/query-modules/_calling_query_modules.mdx
=> [release-2.4.0 < T1011-MG] Graph project feature

docs/reference-guide/security.md
Added documentation for new feature -> label-based access control 
The feature is the extension of access-control with clause privileges
Vla: Resolved https://github.com/memgraph/docs/issues/546
=> Documentation for label-based access control

docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md, docs/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md, docs/reference-guide/query-modules/implement-custom-query-modules/overview.md, docs/reference-guide/query-modules/overview.md, sidebars/sidebarsMemgraph.js
=> [release-2.4.0 < cpp-api] Add C++ query modules API

docs/changelog.md
=> [T1076-MG < MG-label-based-auth] Add changelog entry for label base auth fix

docs/changelog.md
=> [master <] Add v2.4.1 changelog

lab/style-script/gss-functions.md, lab/style-script/gss-graphstyle-directive.md, lab/style-script/gss-graphstyle-map-directive.md, lab/style-script/reference-guide.md
> **Important note:** Please do not merge this before we release the new version of the Lab which will contain all the updates to the GSS noted and documented in this PR.
It contains the documentation for the following updates:
* New GSS graph functions: `Edges`, `Nodes`
* New GSS string functions: `Slice`, `Replace`, `Trim`, `Split`
* New GSS type functions: `IsNumber`, `IsString`, `IsBoolean`, `IsNull`
* New GSS directives: `@GraphStyle`, `@GraphStyle.Map`
=> [master < T2387-CL] Add new GSS functions and directives

docs/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md, memgraph_versioned_docs/version-2.4.0/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md
=> [master<] Add warning about multi-threaded usage of C++ API

docs/connect-to-memgraph/drivers/java.md
I changed the bolt java driver version from Neo4j's to Memgraph's. 
=> [master < Change-from-neo4j-java-driver-to-Memgraph's] Bolt-java-driver-dependency

lab/changelog.md
Add missing releases to the Lab CHANGELOG. Add release dates for all the releases.
=> [master < T2462-PL] Add missing releases to the Lab changelog

docusaurus.config.js
Added width and height parameters for the logo in the footer.
=> [master < fix-logo-in-footer] Fix logo size

docs/changelog.md
=> [release-2.4.2 < T1107-MG] Add changelog for bugfix on iterating over edges

mage/algorithms/machine-learning-graph-analytics/link-prediction-algorithm.md, mage/query-modules/python/gnn-link-prediction.md
Changed URL of the link prediction source repo. Added link prediction to the machine learning algorithms page. 
=> [master < link-prediction-update] Link prediction URL update and machine learning algorithms update.

lab/changelog.md
Add release notes for Lab v2.3.1.
=> [master < T2488-PL] Add release notes for Lab v2.3.1

docs/how-to-guides/work-with-docker.md
=> [master<docker-fix] fix docker command

help-center/overview.md
Updated list of support channels
=> [master < change-support-link] Update list of support channels

memgraph_versioned_docs/version-2.2.1/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.3.0/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.3.1/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.4.0/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.4.1/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.4.2/how-to-guides/work-with-docker.md
propagating the fix to previous versions
=> [master<docker-fix-previous-versions]fix-previous-v

mage/installation/overview.md
=> [master < update-mage-versioning] Update MAGE versioning against MG

mage/query-modules/python/igraphalg.md
=> [master < igraph_support] Igraph query module docs

docs/installation/direct-download-links.md, docs/installation/linux/rpm-installation.md, docs/installation/linux/ubuntu-installation.md
Updated direct download links
Closes (https://github.com/memgraph/docs/issues/558)
=> [master < T-0996-update-direct-download-links] Update direct download links

mage/changelog.md
=> [master < add-mage-changelog] Add MAGE changelog

mage/installation/docker-build.md, mage/installation/source.md
=> Updated mage installation docs

mage/changelog.md
=> [master < fix-changelog-mage] Remove empty line on changelog for MAGE

mage/algorithms/machine-learning-graph-analytics/gnn-algorithm.md
Fix issue that there are no docs for GNN.
=> [master < fix-mage-gnn-impl] Add docs for GNN

mage/query-modules/python/graph-coloring.md
Client had a question about why we return only the node ID in this algorithm. So I modified it to return the actual Vertex and color in int type. This PR is to address the changes.
=> replace outputs

memgraph_versioned_docs/version-2.4.2/installation/direct-download-links.md
Fix links for direct download in version docs 2.4.2.
=> [master < fix-download-links-242] Fix links for direct download

docs/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md, mage/how-to-guides/run-a-query-module.md, mage/installation/docker-build.md, memgraph_versioned_docs/version-2.4.0/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md, memgraph_versioned_docs/version-2.4.1/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md, memgraph_versioned_docs/version-2.4.2/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md
Fixing the docker run command to install mage
FIxing a query module example
Closes https://github.com/memgraph/docs/issues/610
Closes https://github.com/memgraph/docs/issues/608
=> [master<] fixes for issues 608 i 610

memgraph_versioned_docs/version-2.4.2/connect-to-memgraph/drivers/php.md
I updated documentation to follow up on latest changes in bolt library. It contained breaking changes. More details: https://github.com/neo4j-php/Bolt/releases/tag/v5.0.0
=> Updated to latest changes in bolt library

cloud/cloud-connect.md, docs/connect-to-memgraph/drivers/php.md, memgraph_versioned_docs/version-2.4.2/connect-to-memgraph/drivers/php.md
Updated the current version with changes to PHP driver
Need to do: 
Check Cloud connection info
=> [master<241122] Updating connection details for PHP driver

cypher-manual/clauses/unwind.md, cypher-manual/differences-in-cypher-implementations.md, docs/changelog.md
=> Updated changelog

docusaurus.config.js
Added a new link to the docs banner.
=> [master < update-docs-banner] Update docs banner

lab/changelog.md
Add a new changelog for memgraph-lab 2.4.0.
=> Add changelog for memgraph lab 2.4.0

cypher-manual/clauses/return.md, cypher-manual/clauses/with.md, cypher-manual/functions.md
=> Added more examples

docs/changelog.md, docs/reference-guide/configuration.md
=> Added env variables

errors/memgraph/ports.md
=> [master < fix-broken-link-ports] Fix broken link

mage/query-modules/python/gnn-link-prediction.md
=> [master < T542] Gnn link prediction blog post link fix

mage/changelog.md
=> [master < add-mage-1.5-changelog] Add mage 1.5 changelog

cypher-manual/cypher-query-language.md, cypher-manual/differences-in-cypher-implementations.md, docs/how-to-guides/replication.md, memgraph_versioned_docs/version-2.4.0/how-to-guides/replication.md, memgraph_versioned_docs/version-2.4.2/how-to-guides/replication.md, memgraph_versioned_docs/version-2.5.0/how-to-guides/replication.md
Made some fixes stated as issues
Closes https://github.com/memgraph/docs/issues/639
Closes https://github.com/memgraph/docs/issues/621
Closes https://github.com/memgraph/docs/issues/566
=> [master<]solving-issues

src/components/analyticsCall.js
=> Fix analytics

src/components/analyticsCall.js, static/js/load-analytics.js
=> Fix analytics calls

memgraph_versioned_docs/version-2.5.0/connect-to-memgraph/drivers/java.md
I just updated the current version of Java quick start with the new updated.
=> Update Java quick start in current version

docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
Update c++ api docs according to changes made in [PR](https://github.com/memgraph/memgraph/pull/732).
=> [memgraph-2.5.1-release < update-docs-properties-c++-api] Update docs for cpp-api

docs/changelog.md, memgraph_versioned_docs/version-2.5.1/changelog.md
reworded the changelog for memgraph 2.5.1
=> [master < changelog-fixes] changes

mage/changelog.md
=> [master < mage-1.5.1-changelog] MAGE 1.5.1 changelog

docs/changelog.md, docs/installation/direct-download-links.md, memgraph_versioned_docs/version-2.5.1/changelog.md, memgraph_versioned_docs/version-2.5.1/installation/direct-download-links.md
=> [master < direct-link-update-251] Update direct download links

docs/installation/overview.mdx, src/css/custom.scss
Add CSS code that is similar to Docusarus Admonitions.
Closes (link to issue): https://github.com/memgraph/docs/issues/568
=> [master< custom-css-for-danger] Add custom CSS code similar to Docusarus Admonitions

memgraph_versioned_docs/version-2.3.0/installation/overview.mdx, memgraph_versioned_docs/version-2.3.1/installation/overview.mdx, memgraph_versioned_docs/version-2.4.0/installation/overview.mdx, memgraph_versioned_docs/version-2.4.1/installation/overview.mdx, memgraph_versioned_docs/version-2.4.2/installation/overview.mdx, memgraph_versioned_docs/version-2.5.0/installation/overview.mdx, memgraph_versioned_docs/version-2.5.1/installation/overview.mdx
Update styling of waring in few old doc pages.
Closes (link to issue): https://github.com/memgraph/docs/issues/672
=> [master < 672 add admonition to html page based on pr 670] Update styling of some old pages

docs/installation/overview.mdx, memgraph_versioned_docs/version-2.3.1/installation/overview.mdx, memgraph_versioned_docs/version-2.4.0/installation/overview.mdx, memgraph_versioned_docs/version-2.4.1/installation/overview.mdx, memgraph_versioned_docs/version-2.4.2/installation/overview.mdx, memgraph_versioned_docs/version-2.5.0/installation/overview.mdx, memgraph_versioned_docs/version-2.5.1/installation/overview.mdx
Fixed what each image includes
=> [master<230124] docker-images

docs/changelog.md
=> [release-v2.5.2 < changelog-v2.5.2] Add v2.5.2 CHANGELOG

help-center/faq/mage-faq.md
I updated one answer in MAGE FAQ. 
=> [master < update-mage-faq] Update MAGE FAQ

docs/changelog.md, mage/changelog.md, memgraph_versioned_docs/version-2.5.2/changelog.md
Added links to relevant doc pages from changelog. 
=> [master<20230201-lnks] Adding links to changelog

.github/workflows/test-deploy.yml, docs/connect-to-memgraph/drivers/go.md, memgraph_versioned_docs/version-2.5.2/connect-to-memgraph/drivers/go.md
I added a note about Object Modeled Graph for Go programming language.
=> Add note about OMG

cypher-manual/clauses/load-csv.md
Add link to load csv how to from cypher manual
=> [master<230207]add link to load csv how to from cypher manual

src/theme/sections/home-in-browser-data-analysis/home-in-browser-data-analysis.js
Fixed the number of regions for Memgraph Cloud.
=> Fix num of regions on Cloud

cloud/cloud-connect.md, docs/connect-to-memgraph/drivers/go.md, memgraph_versioned_docs/version-2.5.2/connect-to-memgraph/drivers/go.md
I bumped up the Go driver from v4 to v5 and tested it. I also fixed minor typos.
=> Bump up go driver version and fix typos

cloud/cloud-connect.md, docs/connect-to-memgraph/drivers/go.md, docs/connect-to-memgraph/drivers/java.md, docs/connect-to-memgraph/drivers/javascript.md, docs/connect-to-memgraph/drivers/rust.md, memgraph_versioned_docs/version-2.5.2/connect-to-memgraph/drivers/go.md, memgraph_versioned_docs/version-2.5.2/connect-to-memgraph/drivers/java.md, memgraph_versioned_docs/version-2.5.2/connect-to-memgraph/drivers/javascript.md, memgraph_versioned_docs/version-2.5.2/connect-to-memgraph/drivers/rust.md
Currently checking all driver codes. 
**Memgraph docs**
**Cloud docs**
**Cloud (cloud.memgraph.com)**
=> Update drivers instructions

mage/query-modules/python/nxalg.md
The example called for the wrong module.
=> [master<230210] Fix nxalg module

errors/memgraph/modules.md, errors/memgraph/python-modules.md
=> 230214.3 Error fixing

docs/import-data/files/cypherl.md, docs/import-data/files/load-csv-clause.md
Add a tip to LOAD CSV and CYPHERL pages about creating indexes
Closes: https://github.com/memgraph/docs/issues/638
=> [master > 230215.3] Add a tip about creating indexes

docs/reference-guide/indexing.md, docs/under-the-hood/indexing.md, memgraph_versioned_docs/version-2.4.2/under-the-hood/indexing.md, memgraph_versioned_docs/version-2.5.0/reference-guide/indexing.md, memgraph_versioned_docs/version-2.5.0/under-the-hood/indexing.md, memgraph_versioned_docs/version-2.5.1/reference-guide/indexing.md, memgraph_versioned_docs/version-2.5.1/under-the-hood/indexing.md, memgraph_versioned_docs/version-2.5.2/reference-guide/indexing.md, memgraph_versioned_docs/version-2.5.2/under-the-hood/indexing.md
Linked indexes and memory usage
=> [master < 230216.1] Memory usage and indexing

cypher-manual/clauses/match.md, cypher-manual/reading-existing-data.md, docs/under-the-hood/storage.md, memgraph_versioned_docs/version-2.5.0/under-the-hood/storage.md, memgraph_versioned_docs/version-2.5.1/under-the-hood/storage.md, memgraph_versioned_docs/version-2.5.2/under-the-hood/storage.md
Added info about getting the internal ID property. 
=> [master < 230216.2] Matching ids

sidebars/sidebarsGQLAlchemy.js
Fix the sidebar that was accidentally deleted.
=> Fix query builder sidebar

help-center/faq/memgraph-faq.md
Updated the first question in the FAQ.
=> [master < update-faq] Update FAQ

cypher-manual/clauses/clauses.md, cypher-manual/clauses/explain.md, cypher-manual/clauses/profile.md, cypher-manual/clauses/return.md, cypher-manual/extension-clauses.md, cypher-manual/other-features.md, cypher-manual/reading-existing-data.md, docs/reference-guide/optimizing-queries/inspecting-queries.md, memgraph_versioned_docs/version-1.3.0/database-functionalities/inspecting-queries.md, memgraph_versioned_docs/version-1.4.0/database-functionalities/inspecting-queries.md, memgraph_versioned_docs/version-1.5.0/database-functionalities/inspecting-queries.md, memgraph_versioned_docs/version-1.6.0/database-functionalities/inspecting-queries.md, memgraph_versioned_docs/version-1.6.1/database-functionalities/inspecting-queries.md, memgraph_versioned_docs/version-2.0.0/database-functionalities/inspecting-queries.md, memgraph_versioned_docs/version-2.0.1/database-functionalities/inspecting-queries.md, memgraph_versioned_docs/version-2.1.0/database-functionalities/inspecting-queries.md, memgraph_versioned_docs/version-2.1.1/how-to-guides/inspecting-queries.md, memgraph_versioned_docs/version-2.2.0/reference-guide/optimizing-queries/inspecting-queries.md, memgraph_versioned_docs/version-2.2.1/reference-guide/optimizing-queries/inspecting-queries.md, memgraph_versioned_docs/version-2.3.0/reference-guide/optimizing-queries/inspecting-queries.md, memgraph_versioned_docs/version-2.3.1/reference-guide/optimizing-queries/inspecting-queries.md, memgraph_versioned_docs/version-2.4.0/reference-guide/optimizing-queries/inspecting-queries.md, memgraph_versioned_docs/version-2.4.1/reference-guide/optimizing-queries/inspecting-queries.md, memgraph_versioned_docs/version-2.4.2/reference-guide/optimizing-queries/inspecting-queries.md, memgraph_versioned_docs/version-2.5.0/reference-guide/optimizing-queries/inspecting-queries.md, memgraph_versioned_docs/version-2.5.1/reference-guide/optimizing-queries/inspecting-queries.md, memgraph_versioned_docs/version-2.5.2/reference-guide/optimizing-queries/inspecting-queries.md, sidebars/sidebarsCypherManual.js
Added explain and profile clauses to cypher manual
Closes: https://github.com/memgraph/docs/issues/559
Closes https://github.com/memgraph/docs/issues/724
=> [master<230216.4] Cypher clauses

docs/how-to-guides/manage-label-based-access-control.md, docs/reference-guide/security.md
Adding somecode snippets to grant privileges
Closes https://github.com/memgraph/docs/issues/689
=> [master > 230217.1] Adding snippets to label based auth

docs/reference-guide/configuration.md, memgraph_versioned_docs/version-2.5.0/reference-guide/configuration.md, memgraph_versioned_docs/version-2.5.1/reference-guide/configuration.md, memgraph_versioned_docs/version-2.5.2/reference-guide/configuration.md
Added info about Bolt protocol to the config page
Closes: https://github.com/memgraph/docs/issues/684
=> [master<230217.2] Note about the bolt 

docs/how-to-guides/create-backup.md, docs/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.0/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.0/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.1/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.1/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.2/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.2/reference-guide/backup.md
Added info how to restore from backup
Closes https://github.com/memgraph/docs/issues/707
=> [master<230217.3] Restore from backup

docs/how-to-guides/create-backup.md, docs/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.0/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.0/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.1/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.1/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.2/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.2/reference-guide/backup.md
=> Revert "[master<230217.3] Restore from backup"

docs/how-to-guides/create-backup.md, docs/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.0/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.0/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.1/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.1/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.2/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.2/reference-guide/backup.md
=> [master<230217.4] Restore backup

mage/installation/source.md
Add rust and cargo as prereq to building MAGE from source
Closes: https://github.com/memgraph/docs/issues/598
=> [master < 230220.1] Add rust and cargo as prereq 

src/components/callout-box-clickable/callout-box-clickable.module.css, src/theme/sections/home-in-browser-data-analysis/home-in-browser-data-analysis.module.css
Noticed that in the dark mode some text was not visible so I fixed that.
=> Fix colors in dark mode

docs/reference-guide/data-types.md, memgraph_versioned_docs/version-2.5.2/reference-guide/data-types.md
Fix map in localdatetime; add cpp api link
=> Fix map in localdatetime; add cpp api link

docs/getting-started.md, memgraph_versioned_docs/version-2.5.2/getting-started.md
Update getting started description
=> [master<23023] Update getting started description

gqlalchemy/getting-started.md
Small updates on Getting started page on GQLAlchemy docs.
Closes #735
=> Update Getting started with GQLAlchemy

mage/query-modules/python/elasticsearch-synchronization.md
=> [master < T574-FL] Describe Elasticsearch index method

docs/tutorials/graph-modeling.md, mage/query-modules/cpp/cycles.md, memgraph_versioned_docs/version-2.5.0/tutorials/graph-modeling.md, memgraph_versioned_docs/version-2.5.1/tutorials/graph-modeling.md, memgraph_versioned_docs/version-2.5.2/tutorials/graph-modeling.md
=> [master<20230307] Modeling course fixes

docs/changelog.md
=> [master<mamgraph-2-6-changelog] Memgraph 2.6 changelog

gqlalchemy/how-to-guides/query-builder/graph-projection.md, mage/how-to-guides/run-mage-modules-on-subgraphs.md, sidebars/sidebarsGQLAlchemy.js
Recently implemented graph projection feature has been added to GQLAlchemy. This how to guide shows how to use it.
=> [master < T0123-GA] graph projections how to guide

docs/installation/overview.mdx
Added minimum and recommended sys req.
=> [master<20230306-sys-req] Adding system requirements 

gqlalchemy/changelog.md
=> [master<] changelog update gqla

memgraph_versioned_docs/version-2.6.0/installation/overview.mdx
=> [master < ]sys-req

memgraph_versioned_docs/version-2.5.0/reference-guide/graph-algorithms.md, memgraph_versioned_docs/version-2.5.1/reference-guide/graph-algorithms.md, memgraph_versioned_docs/version-2.5.2/reference-guide/graph-algorithms.md, memgraph_versioned_docs/version-2.6.0/reference-guide/graph-algorithms.md
Fixed an example of all shortest docs.
=> [master<230317] All shortest section has weighted example

help-center/faq/mage-faq.md, help-center/faq/memgraph-faq.md, help-center/faq/memgraph-lab-faq.md
Updated the FAQ page to be consistent with the Airtable FAQ
=> [master < ] Update the FAQ page

lab/changelog.md
Fix the node/relationship limits for the graph preview.
=> Fix the node/relationship limits for the graph preview

docs/installation/direct-download-links.md, memgraph_versioned_docs/version-2.6.0/installation/direct-download-links.md
Add the Ubuntu ARM link to the list of direct download links.
=> [master<update-direct-download-links] Add Ubuntu ARM link

docs/import-data/files/cypherl.md, docs/import-data/files/load-csv-clause.md, memgraph_versioned_docs/version-2.5.0/import-data/files/load-csv-clause.md, memgraph_versioned_docs/version-2.5.1/import-data/files/load-csv-clause.md, memgraph_versioned_docs/version-2.5.2/import-data/files/load-csv-clause.md, memgraph_versioned_docs/version-2.6.0/import-data/files/cypherl.md, memgraph_versioned_docs/version-2.6.0/import-data/files/load-csv-clause.md
Add an example of a query that loads all data as strings
Closes (link to issue): https://github.com/memgraph/docs/issues/774
=> [master<20230324] Give an example of LOAD CSV for all strings

gqlalchemy/installation.md
I updated installation prerequisites: CMake -> all pymgclient prerequisites. 
Closes #754
=> Update GQLAlchemy installation prerequisites

cypher-manual/functions.md, docs/connect-to-memgraph/mgconsole.md, docs/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.1.1/connect-to-memgraph/mgconsole.md, memgraph_versioned_docs/version-2.2.1/connect-to-memgraph/mgconsole.md, memgraph_versioned_docs/version-2.2.1/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.3.0/connect-to-memgraph/mgconsole.md, memgraph_versioned_docs/version-2.3.0/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.3.1/connect-to-memgraph/mgconsole.md, memgraph_versioned_docs/version-2.3.1/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.4.0/connect-to-memgraph/mgconsole.md, memgraph_versioned_docs/version-2.4.0/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.4.1/connect-to-memgraph/mgconsole.md, memgraph_versioned_docs/version-2.4.1/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.4.2/connect-to-memgraph/mgconsole.md, memgraph_versioned_docs/version-2.4.2/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.5.0/connect-to-memgraph/mgconsole.md, memgraph_versioned_docs/version-2.5.0/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.5.1/connect-to-memgraph/mgconsole.md, memgraph_versioned_docs/version-2.5.1/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.5.2/connect-to-memgraph/mgconsole.md, memgraph_versioned_docs/version-2.5.2/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.6.0/connect-to-memgraph/mgconsole.md, memgraph_versioned_docs/version-2.6.0/how-to-guides/work-with-docker.md
- Fixes spelling mistakes listed in https://github.com/memgraph/docs/issues/778
- Fixed styling listed in https://github.com/memgraph/docs/issues/775
- Fixed commands listed in https://github.com/memgraph/docs/issues/806
- https://github.com/memgraph/docs/issues/778 
- https://github.com/memgraph/docs/issues/775
- https://github.com/memgraph/docs/issues/806
=> Various minor fixes [master < minor-fixes-wn13-2023]

docs/how-to-guides/indexes.md, docs/reference-guide/analyze_graph.md, docs/reference-guide/indexing.md, sidebars/sidebarsMemgraph.js
Added the docs page about index improvements. The blog post link will be changed when published.
PR this doc page is related to: https://github.com/memgraph/memgraph/pull/812
=> [master < T607-FL] Index optimization

cypher-manual/clauses/call.md, cypher-manual/clauses/clauses.md, sidebars/sidebarsCypherManual.js
The changes in docs correspond to the subqueries feature. The main addition is the CALL { query } keyword.
=> Add subqueries docs

docs/changelog.md
Chagelog for features and bugfixes in Memgraph 2.7.0
=> [master<]Changelog for Memgraph 2.7.0

docs/how-to-guides/manage-label-based-access-control.md
Update documentation page that lists for user privileges
https://github.com/memgraph/docs/issues/805
=> [master < update-label-based-access-control] Update documentation page that lists for user privileges

docs/changelog.md, memgraph_versioned_docs/version-2.7.0/changelog.md
updated links on changelog to the connected docs
=> [master<] update-links-on-changelog

docs/reference-guide/security.md, memgraph_versioned_docs/version-2.7.0/reference-guide/security.md
Add a link to configuration docs page.
=> [master < 2023-04-07-add-link] Add link to configuration

gqlalchemy/how-to-guides/loaders/import-table-data-to-graph-database.md
How to guide for loading data from table format to Memgraph in GQLAlchemy had some bugs and needed improvements.
https://github.com/memgraph/gqlalchemy/issues/234
=> [master < T01238-GA] Improve GQLAlchemy table-to-graph loaders how-to

docs/changelog.md, docs/reference-guide/backup.md, docs/reference-guide/configuration.md
=> [release 2.8 < MG-parallel-recovery] Document parallel recovery related configs

mage/query-modules/cpp/pagerank_online.md
Changed the examples from pagerank.get to pagerank_online.get
=> [master<20231904] Online PageRank fix

lab/changelog.md
Added changelog from 
https://www.notion.so/memgraph/Lab-v2-6-0-Multiple-query-results-a23fd3634e1040bb89c643bdf6719846
=> [master<changelog-lab-260] Lab 2.6.0 changelog

cypher-manual/clauses/call.md, docs/reference-guide/storage-modes.md, memgraph_versioned_docs/version-2.7.0/reference-guide/storage-modes.md
Fix typos in two places.
- https://github.com/memgraph/docs/issues/819
- https://github.com/memgraph/docs/issues/827
=> Fix typos [master<819-fix-typos-20230424]

docs/how-to-guides/create-backup.md, docs/how-to-guides/work-with-docker.md, docs/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.0/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.0/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.5.0/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.1/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.1/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.5.1/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.2/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.2/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.5.2/reference-guide/backup.md, memgraph_versioned_docs/version-2.6.0/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.6.0/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.6.0/reference-guide/backup.md, memgraph_versioned_docs/version-2.7.0/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.7.0/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.7.0/reference-guide/backup.md
Ppl were getting confused about the data directory and that it actually means the snapshots dir and wal dir... so i tried to explain that a bit better
+ the how to guide was missing a restart step
=> [master<20230420] Improve backup and restore docs

help-center/faq/memgraph-faq.md
Update the FAQ with info about indexes for import speed. 
Closes #830
=> Update import info with indexing in FAQ

docs/how-to-guides/query-modules.md, docs/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md, docs/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md, docs/reference-guide/query-modules/implement-custom-query-modules/overview.md, docs/reference-guide/query-modules/overview.md, mage/how-to-guides/create-a-new-module-python.md, memgraph_versioned_docs/version-2.7.0/how-to-guides/query-modules.md, memgraph_versioned_docs/version-2.7.0/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md, memgraph_versioned_docs/version-2.7.0/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md, memgraph_versioned_docs/version-2.7.0/reference-guide/query-modules/implement-custom-query-modules/overview.md, memgraph_versioned_docs/version-2.7.0/reference-guide/query-modules/overview.md
I added how-to guide on how to install external Python libraries. 
Closes #800
=> Add tip on how to install additional Python libraries

docs/how-to-guides/manage-user-privileges.md, docs/reference-guide/security.md, memgraph_versioned_docs/version-2.7.0/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.7.0/reference-guide/security.md
Update docs with new info on creating new users when an email address is used as username.
https://github.com/memgraph/docs/issues/801
=> [master < 801-formatting-email-username-when-creating-an-user] Update docs with new info 

docs/installation/overview.mdx, lab/getting-started.md, lab/installation/overview.md, memgraph_versioned_docs/version-2.7.0/installation/overview.mdx
Added information about a Docker image that only includes Lab and MemgraphDB.
Add feature about stream management to Lab overview
Closes #787
Closes #776
=> [master<787] Add info about DB+Lab Docker image

docs/connect-to-memgraph/mgconsole.md, memgraph_versioned_docs/version-2.7.0/connect-to-memgraph/mgconsole.md
I've added config flags and info about non-interacive mode to mgconsole
Closes #845 
Closes #791
=> [master<845] Add info about mgconsole

docs/import-data/overview.md
=> [677<677-1] Add overview page for import

docs/export-data/overview.md, sidebars/sidebarsMemgraph.js
Add information about exporting
=> [622<622-2] Add export section

docs/import-data/overview.md
Adding info about backup and restoring on import overview
=> [677<677.3] Info about backup on import

docs/how-to-guides/managing-python-environment.md, docs/import-data/files/load-csv-clause.md, docs/reference-guide/storage-modes.md
Added info about indexes and analytical mode
=> [677<677.4] Update load csv

docs/import-data/files/load-json.md, docs/import-data/files/overview.md, docs/import-data/overview.md
Added info about importing data to JSON
=> [677<677-5] JSON import

gqlalchemy/tutorials/overview.md
=> [master < doc-fix-20230505] Delete unused files

docs/connect-to-memgraph/mgconsole.md
Changed how you execute mgconsole from Docker container. 
Closes #858
=> [master<858] mgconsole exec

docs/how-to-guides/replication.md, docs/reference-guide/replication.md, docs/under-the-hood/replication.md, memgraph_versioned_docs/version-2.7.0/how-to-guides/replication.md, memgraph_versioned_docs/version-2.7.0/reference-guide/replication.md, memgraph_versioned_docs/version-2.7.0/under-the-hood/replication.md
I updated the how-to guide, reference guide and under-the-hood content of Replication. These are just small changes, mostly related to Docker run commands.
=> Update replication docs

docs/how-to-guides/enterprise-features.md, docs/reference-guide/enterprise-features.md, sidebars/sidebarsMemgraph.js
I've added overview pages for Enterprise features to the How to and Reference guide sections.
https://github.com/memgraph/docs/issues/804
=> Add overview pages for Enterprise features

docs/how-to-guides/manage-label-based-access-control.md, docs/how-to-guides/manage-user-privileges.md, docs/how-to-guides/manage-users-using-ldap.md, memgraph_versioned_docs/version-2.0.0/database-functionalities/manage-user-privileges.md, memgraph_versioned_docs/version-2.0.1/database-functionalities/manage-user-privileges.md, memgraph_versioned_docs/version-2.1.0/database-functionalities/manage-user-privileges.md, memgraph_versioned_docs/version-2.1.1/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.2.0/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.2.1/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.3.0/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.3.1/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.4.0/how-to-guides/manage-label-based-access-control.md, memgraph_versioned_docs/version-2.4.0/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.4.1/how-to-guides/manage-label-based-access-control.md, memgraph_versioned_docs/version-2.4.1/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.4.2/how-to-guides/manage-label-based-access-control.md, memgraph_versioned_docs/version-2.4.2/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.5.0/how-to-guides/manage-label-based-access-control.md, memgraph_versioned_docs/version-2.5.0/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.5.1/how-to-guides/manage-label-based-access-control.md, memgraph_versioned_docs/version-2.5.1/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.5.2/how-to-guides/manage-label-based-access-control.md, memgraph_versioned_docs/version-2.5.2/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.6.0/how-to-guides/manage-label-based-access-control.md, memgraph_versioned_docs/version-2.6.0/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.6.0/how-to-guides/manage-users-using-ldap.md, memgraph_versioned_docs/version-2.7.0/how-to-guides/manage-label-based-access-control.md, memgraph_versioned_docs/version-2.7.0/how-to-guides/manage-user-privileges.md, memgraph_versioned_docs/version-2.7.0/how-to-guides/manage-users-using-ldap.md
Replaced the warning on enterprise edition pages.
https://github.com/memgraph/docs/issues/873
=> Replace the warning on enterprise edition pages

docs/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.2.1/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.3.0/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.3.1/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.4.0/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.4.1/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.4.2/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.5.0/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.5.1/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.5.2/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.6.0/how-to-guides/work-with-docker.md, memgraph_versioned_docs/version-2.7.0/how-to-guides/work-with-docker.md
Add mgconsole to the list of installed components when using Docker images. 
Closes (link to issue):  https://github.com/memgraph/docs/issues/865
=> [master <865-check-if-we] Add mgconsole to the list of installed components 

cypher-manual/import-data.md, gqlalchemy/import-data.md
Fix two typos.
https://github.com/memgraph/docs/issues/857
=> [master < 857-fix-this-typo] Fix typos

docs/how-to-guides/create-backup.md, docs/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.0/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.0/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.1/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.1/reference-guide/backup.md, memgraph_versioned_docs/version-2.5.2/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.5.2/reference-guide/backup.md, memgraph_versioned_docs/version-2.6.0/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.6.0/reference-guide/backup.md, memgraph_versioned_docs/version-2.7.0/how-to-guides/create-backup.md, memgraph_versioned_docs/version-2.7.0/reference-guide/backup.md
Updated the backup and restore process again. 
Wrong branch name, the issue is 859
Closes #859
=> [master<873] Backup and restore update

docs/installation/linux/debian-installation.md, docs/installation/linux/docker-db-installation.md, docs/installation/linux/docker-installation.md, docs/installation/linux/rpm-installation.md, docs/installation/linux/ubuntu-installation.md, docs/installation/macos/docker-db-installation.md, docs/installation/macos/docker-installation.md, docs/installation/windows/docker-db-installation.md, docs/installation/windows/docker-installation.md, docs/installation/windows/wsl-installation.md, docs/templates/_backward_compatibility_warning.mdx
Replaced warning with template.
https://github.com/memgraph/docs/issues/795
=> Replace warning with template

gqlalchemy/installation.md
I added the information on the installation of GQLAlchemy for Zsh terminals.
Closes #884
=> Update GQLAlchemy installation for zsh terminal

docusaurus.config.js, package-lock.json, package.json
Added data for new Algolia search app.
https://github.com/memgraph/docs/issues/887
=> [master < 887-check-algolia-search] Add new Algolia data

docs/reference-guide/enterprise-features.md, memgraph_versioned_docs/version-2.8.0/reference-guide/enterprise-features.md
Updated paragraph about security.
https://github.com/memgraph/docs/issues/898
=> [master < 898-fix-security-section] Update security paragraph

docs/changelog.md, memgraph_versioned_docs/version-2.8.0/changelog.md
User reported typo in changelog
=> Fix typo in Changelog

docs/changelog.md, memgraph_versioned_docs/version-2.7.0/changelog.md, memgraph_versioned_docs/version-2.8.0/changelog.md, src/components/VideoBySide.js
Add React component for embedding video.
=> [master < new-layout-for-changelog] Add video embeds to changelog

cloud/getting-started.md, docs/tutorials/first-steps-with-memgraph.md, src/components/EmbedYTVideo.js
Updated video embeds.
https://github.com/memgraph/docs/issues/904
=> [master < 904] Update video embeds

cypher-manual/clauses/call.md
Links were not working correctly on h1, so I switched all h1 to h2 and h2 to h3, like we usually write. 
=> Fix header size

memgraph_versioned_docs/version-2.8.0/how-to-guides/networkx.md
Fixed broken link in the Where to next section.
=> [master< fix-links-20230525] Fix broken link

src/css/custom.scss
Added CSS code for H4.
Closes (link to issue): https://github.com/memgraph/docs/issues/908
=> [master < 908-bigger-h4] Add H4 styling

docs/tutorials/migrate-from-neo4j.md
=> Add small fixes to migration guide

docs/tutorials/migrate-from-neo4j.md
Add a video to the top of the page.
=> [master < add-video-20230602] Add video

memgraph_versioned_docs/version-2.7.0/reference-guide/backup.md, memgraph_versioned_docs/version-2.8.0/reference-guide/backup.md
Update versioned docs related to backup.
=> [master < update-old-backup-docs-20230620] Update versioned docs

docusaurus.config.js, static/js/custom-gtag.js
=> [master <ga4-code] Add GA4 code

docusaurus.config.js, static/js/custom-gtag.js
I've removed GA4 code. Something is not working as it should. I'll try to find a fix in a new branch.
=> [master < rempve-ga4] Remove ga4 code

docusaurus.config.js
=> [master < configure-gtag] Configure plugin google gtag

docusaurus.config.js
=> [master < remove-gtag] Remove gtag

cypher-manual/clauses/match.md
I've updated the admonition code
=> [master < fix-typo-match] Update admonition code

cypher-manual/clauses/load-csv.md, docs/import-data/files/load-csv-clause.md
The NULLIF command enables for users to specify a character sequence which will result in a null inside LOAD CSV.
=> [master < T921] Add documentation for NULLIF command in LOAD CSV

cypher-manual/clauses/match.md
I updated the Cypher Manual with the information about running multiple MATCH queries.
=> Add multiple match in MATCH clause

docs/reference-guide/analyze-graph.md
ANALYZE GRAPH query has been updated to also output average degree of the vertices, as well as make some optimizations in the query planner. 
=> Add analyze graph degrees to docs

docs/reference-guide/graph-algorithms.md, memgraph_versioned_docs/version-2.5.0/reference-guide/graph-algorithms.md, memgraph_versioned_docs/version-2.5.1/reference-guide/graph-algorithms.md, memgraph_versioned_docs/version-2.5.2/reference-guide/graph-algorithms.md, memgraph_versioned_docs/version-2.6.0/reference-guide/graph-algorithms.md, memgraph_versioned_docs/version-2.7.0/reference-guide/graph-algorithms.md, memgraph_versioned_docs/version-2.8.0/reference-guide/graph-algorithms.md
Added another example to the Depth-First search algorithm after the user asked about using DFS with multiple relationship labels on Discord.
=> Add another DFS example

lab/changelog.md
=> fix-the-bullet-list

docs/reference-guide/query-modules/implement-custom-query-modules/api/c-api.md, docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md, docs/reference-guide/query-modules/implement-custom-query-modules/api/python-api.md, docs/reference-guide/query-modules/implement-custom-query-modules/custom-query-module-example.md
This diff adds docs for batched procedures, both API and a few examples in Python, C, and C++.
PR this doc page is related to:
=> Add docs for batched procedures

docs/reference-guide/analyze-graph.md
Changed the flow of the Analyze graph docs a bit so it feels more unified
=> [master<] Improve analyze graph docs

lab/changelog.md
Created a changelog for Lab 2.7.1
=> [master<] Changelog for Lab 2.7.1

docs/how-to-guides/replication.md, docs/reference-guide/configuration.md, docs/reference-guide/replication.md
Added a new config flag for replication and changed the docs accordingly. 
=> [master<] Replication config flag

docs/changelog.md
Changelog for Memgraph v2.9.0
- need to add relevant links once all is merged
=> [master<] Memgraph 2.9.0 - changelog

sidebars/sidebarsMAGE.js
Add a link to  "query-modules/python/migrate" in the sidebar.
=> [master < add-module-to-menu] Add one menu item

mage/changelog.md
=> [master<] MAGE changelog 1.8.0

docs/installation/direct-download-links.md, memgraph_versioned_docs/version-2.7.0/installation/direct-download-links.md, memgraph_versioned_docs/version-2.8.0/installation/direct-download-links.md
=> [master < update-direct-download-links] Update links for MG 2.9

mage/changelog.md, sidebars/sidebarsMAGE.js
Missing side menu and wrong module name
=> [master<] Side menu and module name 

docs/changelog.md, mage/changelog.md, memgraph_versioned_docs/version-2.9.0/changelog.md
=> [master<] Links

docs/connect-to-memgraph/drivers/javascript.md
Server now can use the `tx_timeout` feature on transactions, ATM only neo4j-driver can use it. Updated documentation with example usage.
PR this doc page is related to: memgraph/memgraph#1046
=> [master <] Examples of using tx_timeout feature

docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
Added docs for remove label function on cpp api.
=> [master < T595] Add docs for remove label function on cpp api

docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
Added documentation for changes done in C++ API which were needed for new MAGE query modules.
[PR1093](https://github.com/memgraph/memgraph/pull/1093)
[PR1103](https://github.com/memgraph/memgraph/pull/1103)
[PR1127](https://github.com/memgraph/memgraph/pull/1127)
=> [master<] Cpp api changes value

docs/reference-guide/configuration.md, docs/reference-guide/query-modules/load-call-query-modules.md
Added docs for a new config flag that allows you to map procedures
=> [master<] Callable mappings path

docs/how-to-guides/manage-user-privileges.md, docs/reference-guide/backup.md, docs/reference-guide/configuration.md, docs/reference-guide/multi-tenancy.md, docs/reference-guide/security.md, sidebars/sidebarsMemgraph.js
Reference guide for multi-tenancy has been added.
PR this doc page is related to: [952](https://github.com/memgraph/memgraph/pull/952)
=> [master<]Added reference guide for multi-tenancy

docs/changelog.md, memgraph_versioned_docs/version-2.10.0/changelog.md
Added a link and more info into changelog
=> [master<] Changelog

lab/changelog.md
=> [master<] Lab changelog

mage/changelog.md
Updated links on the changelog
=> [master<] Updated links

mage/query-modules/cpp/create.md
=> [E-mage-create-docs < E-create-docs-matija] Write part of create docs for matija's functions

lab/changelog.md
=> New: Update changelog.md with Lab v2.8.1

docs/installation/linux/docker-installation.md, docs/installation/macos/docker-installation.md, docs/installation/windows/docker-installation.md
Updated Docker related docs with instructions on how to run, stop and start named instances.
=> [maser < update-docker-docs] Update docker documentation

docs/installation/direct-download-links.md, memgraph_versioned_docs/version-2.10.1/installation/direct-download-links.md
Updated direct download links for Memgraph 2.10.1
=> [master < 1009-update...] Update direct download links

mage/query-modules/cpp/node.md
=> Add node function

docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
Wrote docs in cpp-api for ToString functions.
PR this doc page is related to:  https://github.com/memgraph/memgraph/pull/1140
=> [master < cpp-api-ToString] Write docs for cpp-api-ToString

docs/reference-guide/query-modules/implement-custom-query-modules/api/cpp-api.md
Add docs for cpp-api SetTo and SetFrom
[PR1221](https://github.com/memgraph/memgraph/pull/1221)
=> [master < cpp-api] Add from and to docs to cpp api
